language: dart

dart:
  - stable
  - dev

dart_task:
  - test
  - dartfmt
  - dartanalyzer: --fatal-warnings --fatal-infos .

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache
